name: maybec.at
markdown: kramdown
highligther: pygments
timezone: Europe/Stockholm
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
url: https://maybec.at
author: Olov Johansson 
gems:
    - jekyll-feed
sass:
  style: compressed
